sudo: required
before_install:
- sudo apt-get -qq update
- sudo apt-get install opam
- git clone https://bitbucket.org/Peter_Sewell/lem.git
- cd lem
- make
- cd ..
- export PATH=./lem:$PATH
script:
- make lem-ocaml
- make lem-thy
